version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fgo-scenes-api"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-wkgxsl098x0i"
s3_prefix = "fgo-scenes-api"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
