AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  fgo-scenes-api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
  Api:
    Cors:
      AllowMethods: "'GET,POST,OPTIONS'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'https://tenkoh.github.io'"
      AllowCredentials: "'*'"

Resources:
  ImageGenerateFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: image_generator/
      Handler: app.lambda_handler
      Runtime: python3.8
      Events:
        ImageGenerate:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /muramasala
            Method: post
  ImGenerateLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ImageGenerateFunction}
      RetentionInDays: 7

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  ImageGenerateApi:
    Description: "API Gateway endpoint URL for Prod stage for Image Generate function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/muramasala/"
  ImageGenerateFunction:
    Description: "Image Generate Lambda Function ARN"
    Value: !GetAtt ImageGenerateFunction.Arn
  ImageGenerateFunctionIamRole:
    Description: "Implicit IAM Role created for Image Generate function"
    Value: !GetAtt ImageGenerateFunctionRole.Arn
